/** Estilo editorial Syng — agenda (negro · marfil · champagne) */
import { L } from './avisoLuxury'

export { L }

export const A = {
  screen: {
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    minHeight: 0,
    overflow: 'hidden',
    background: L.ink,
    color: L.ivory,
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '14px 20px 10px',
    paddingTop: 'max(14px, env(safe-area-inset-top))',
    borderBottom: `1px solid rgba(196,169,98,0.2)`,
    flexShrink: 0,
    background: L.ink,
  },
  headerTitle: {
    fontFamily: L.serif,
    fontSize: 22,
    fontWeight: 400,
    color: L.ivory,
    letterSpacing: '-0.02em',
    flex: 1,
  },
  badge: {
    fontSize: 10,
    fontWeight: 500,
    letterSpacing: '0.28em',
    textTransform: 'uppercase',
    color: L.champagne,
  },
  card: {
    margin: '0 16px 24px',
    padding: '14px 16px',
    background: L.champagneLight,
    border: `1px solid ${L.champagneBorder}`,
    borderRadius: 2,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    cursor: 'pointer',
    WebkitTapHighlightColor: 'transparent',
  },
  fab: {
    position: 'fixed',
    bottom: 'calc(76px + env(safe-area-inset-bottom))',
    right: 20,
    zIndex: 400,
    width: 56,
    height: 56,
    borderRadius: 2,
    background: L.ivory,
    color: L.ink,
    border: `1px solid ${L.ivory}`,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 8px 32px rgba(0,0,0,0.45)',
    WebkitTapHighlightColor: 'transparent',
  },
  sectionTitle: {
    fontFamily: L.serif,
    fontSize: 24,
    fontWeight: 400,
    color: L.ivory,
    letterSpacing: '-0.02em',
    margin: 0,
  },
  navBtn: {
    background: 'none',
    border: 'none',
    fontSize: 22,
    color: L.champagne,
    cursor: 'pointer',
    padding: '4px 12px',
    minWidth: 44,
    minHeight: 44,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    WebkitTapHighlightColor: 'transparent',
  },
  taskPending: {
    background: 'rgba(255,255,255,0.06)',
    border: `1px solid ${L.champagneBorder}`,
    borderRadius: 2,
    opacity: 1,
  },
  taskDone: {
    background: 'rgba(255,255,255,0.02)',
    border: `1px solid rgba(196,169,98,0.18)`,
    borderRadius: 2,
    opacity: 0.5,
  },
  tagPersonal: {
    fontSize: 11,
    fontWeight: 500,
    padding: '2px 9px',
    borderRadius: 2,
    border: `1px solid ${L.champagneBorder}`,
    color: L.champagne,
    background: L.champagneLight,
  },
  tagGroup: {
    fontSize: 11,
    fontWeight: 500,
    padding: '2px 9px',
    borderRadius: 2,
    border: '1px solid rgba(52,199,89,0.35)',
    color: '#6ee7a0',
    background: 'rgba(52,199,89,0.08)',
  },
  body: {
    flex: 1,
    overflowY: 'auto',
    WebkitOverflowScrolling: 'touch',
  },
  scrollArea: {
    flex: 1,
    overflowY: 'auto',
    WebkitOverflowScrolling: 'touch',
    minHeight: 0,
  },
  stickyHeader: {
    position: 'sticky',
    top: 0,
    zIndex: 10,
    display: 'flex',
    alignItems: 'center',
    padding: '14px 20px',
    paddingTop: 'max(14px, env(safe-area-inset-top))',
    borderBottom: `1px solid rgba(196,169,98,0.2)`,
    background: L.ink,
    flexShrink: 0,
  },
  section: {
    background: L.champagneLight,
    border: `1px solid ${L.champagneBorder}`,
    borderRadius: 2,
    margin: '12px 16px 0',
    overflow: 'hidden',
  },
  sectionLabel: {
    margin: 0,
    fontSize: 10,
    fontWeight: 500,
    letterSpacing: '0.28em',
    textTransform: 'uppercase',
    color: L.champagne,
    padding: '10px 16px 4px',
  },
  row: {
    display: 'flex',
    alignItems: 'center',
    padding: '13px 16px',
    cursor: 'pointer',
    borderTop: `1px solid rgba(196,169,98,0.12)`,
  },
  input: {
    width: '100%',
    boxSizing: 'border-box',
    padding: '11px 14px',
    borderRadius: 2,
    border: `1px solid ${L.champagneBorder}`,
    fontSize: 16,
    color: L.ivory,
    fontFamily: 'inherit',
    outline: 'none',
    background: 'rgba(255,255,255,0.04)',
  },
  btnPrimary: {
    flex: 1,
    padding: '12px',
    borderRadius: 2,
    border: `1px solid ${L.ivory}`,
    background: L.ivory,
    color: L.ink,
    fontSize: 13,
    fontWeight: 600,
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
    cursor: 'pointer',
  },
  btnSecondary: {
    flex: 1,
    padding: '12px',
    borderRadius: 2,
    border: `1px solid ${L.champagneBorder}`,
    background: 'transparent',
    color: L.ivoryMuted,
    fontSize: 14,
    cursor: 'pointer',
  },
  btnOutline: {
    width: '100%',
    minHeight: 44,
    borderRadius: 2,
    border: `1px solid ${L.champagneBorder}`,
    background: 'transparent',
    color: L.ivoryMuted,
    fontSize: 14,
    fontWeight: 500,
    cursor: 'pointer',
  },
  btnNew: {
    background: L.ivory,
    color: L.ink,
    border: `1px solid ${L.ivory}`,
    borderRadius: 2,
    padding: '8px 14px',
    fontSize: 12,
    fontWeight: 600,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    cursor: 'pointer',
    flexShrink: 0,
    WebkitTapHighlightColor: 'transparent',
  },
  btnDanger: {
    width: '100%',
    padding: '14px',
    borderRadius: 2,
    border: '1px solid rgba(224,82,82,0.35)',
    background: 'rgba(224,82,82,0.08)',
    color: '#E05252',
    fontSize: 14,
    fontWeight: 600,
    cursor: 'pointer',
  },
  groupCard: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    padding: '14px 16px',
    background: L.champagneLight,
    border: `1px solid ${L.champagneBorder}`,
    borderRadius: 2,
    cursor: 'pointer',
    WebkitTapHighlightColor: 'transparent',
  },
  notifUnread: {
    background: L.champagneLight,
    border: `1px solid ${L.champagneBorder}`,
  },
  notifRead: {
    background: 'rgba(255,255,255,0.03)',
    border: `1px solid rgba(196,169,98,0.15)`,
  },
  avatar: {
    width: 80,
    height: 80,
    borderRadius: 2,
    background: L.champagneLight,
    border: `1px solid ${L.champagneBorder}`,
    color: L.champagne,
    fontSize: 30,
    fontFamily: L.serif,
    fontWeight: 400,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
}
