/** Estilo editorial Syng — agenda (negro · marfil · champagne) */
import { L } from './avisoLuxury'

export { L }

export const A = {
  screen: {
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    minHeight: 0,
    overflow: 'hidden',
    background: L.ink,
    color: L.ivory,
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '14px 20px 10px',
    paddingTop: 'max(14px, env(safe-area-inset-top))',
    borderBottom: `1px solid rgba(196,169,98,0.2)`,
    flexShrink: 0,
    background: L.ink,
  },
  headerTitle: {
    fontFamily: L.serif,
    fontSize: 22,
    fontWeight: 400,
    color: L.ivory,
    letterSpacing: '-0.02em',
    flex: 1,
  },
  badge: {
    fontSize: 10,
    fontWeight: 500,
    letterSpacing: '0.28em',
    textTransform: 'uppercase',
    color: L.champagne,
  },
  card: {
    margin: '0 16px 24px',
    padding: '14px 16px',
    background: L.champagneLight,
    border: `1px solid ${L.champagneBorder}`,
    borderRadius: 2,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    cursor: 'pointer',
    WebkitTapHighlightColor: 'transparent',
  },
  fab: {
    position: 'fixed',
    bottom: 'calc(76px + env(safe-area-inset-bottom))',
    right: 20,
    zIndex: 400,
    width: 56,
    height: 56,
    borderRadius: 2,
    background: L.ivory,
    color: L.ink,
    border: `1px solid ${L.ivory}`,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 8px 32px rgba(0,0,0,0.45)',
    WebkitTapHighlightColor: 'transparent',
  },
  sectionTitle: {
    fontFamily: L.serif,
    fontSize: 24,
    fontWeight: 400,
    color: L.ivory,
    letterSpacing: '-0.02em',
    margin: 0,
  },
  navBtn: {
    background: 'none',
    border: 'none',
    fontSize: 22,
    color: L.champagne,
    cursor: 'pointer',
    padding: '4px 12px',
    minWidth: 44,
    minHeight: 44,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    WebkitTapHighlightColor: 'transparent',
  },
  taskPending: {
    background: 'rgba(255,255,255,0.06)',
    border: `1px solid ${L.champagneBorder}`,
    borderRadius: 2,
    opacity: 1,
  },
  taskDone: {
    background: 'rgba(255,255,255,0.02)',
    border: `1px solid rgba(196,169,98,0.18)`,
    borderRadius: 2,
    opacity: 0.5,
  },
  tagPersonal: {
    fontSize: 11,
    fontWeight: 500,
    padding: '2px 9px',
    borderRadius: 2,
    border: `1px solid ${L.champagneBorder}`,
    color: L.champagne,
    background: L.champagneLight,
  },
  tagGroup: {
    fontSize: 11,
    fontWeight: 500,
    padding: '2px 9px',
    borderRadius: 2,
    border: '1px solid rgba(52,199,89,0.35)',
    color: '#6ee7a0',
    background: 'rgba(52,199,89,0.08)',
  },
}
