export const CATALOGOS = {
  es: {
    'Lácteos': ['Crema','Crema ácida','Jocoque','Jocoque seco','Leche condensada','Leche descremada','Leche entera','Leche evaporada','Leche light','Leche sin lactosa','Mantequilla','Mantequilla sin sal','Margarina','Queso amarillo','Queso Chihuahua','Queso cottage','Queso crema','Queso fresco','Queso manchego','Queso Oaxaca','Queso panela','Queso parmesano','Queso ricotta','Requesón','Yogur bebible','Yogur griego','Yogur natural','Yogur sin azúcar','Crema para batir','Leche de almendras'],
    'Carnes y embutidos': ['Bistec de res','Carne de cerdo','Carne molida','Carne para asar','Chambarete','Chuleta de cerdo','Chorizo','Costilla de res','Costilla de cerdo','Filete de res','Jamón','Jamón serrano','Lomo de cerdo','Milanesa de res','Milanesa de pollo','Pechuga de pollo','Pierna de pollo','Pollo entero','Salchicha','Salchicha de pavo','Tocino','Atún en lata','Camarón','Filete de pescado','Mariscos','Salami','Mortadela','Pepperoni','Longaniza','Barbacoa'],
    'Frutas y verduras': ['Aguacate','Ajo','Apio','Arándanos','Betabel','Brócoli','Calabacita','Calabaza','Cebolla','Cebolla morada','Cebollín','Chile ancho','Chile chipotle','Chile güero','Chile habanero','Chile jalapeño','Chile mulato','Chile pasilla','Chile poblano','Chile serrano','Chícharo','Cilantro','Col','Coliflor','Durazno','Ejote','Elote','Espárrago','Espinaca','Fresa','Granada','Guayaba','Higo','Hongos','Jitomate','Kiwi','Lechuga','Limón','Mandarina','Mango','Manzana','Melón','Naranja','Nopales','Papa','Papaya','Pepino','Pera','Piña','Pimiento','Plátano','Sandía','Tomate','Uvas','Zanahoria','Zucchini','Camote'],
    'Abarrotes': ['Aceite','Aceite de oliva','Arroz blanco','Arroz integral','Atún','Azúcar','Canela','Chocolate','Consomé de pollo','Crema de cacahuate','Frijol negro','Frijol pinto','Gelatina','Harina','Ketchup','Lentejas','Maicena','Miel de abeja','Mostaza','Pasta','Pimienta negra','Sal','Salsa catsup','Salsa picante','Salsa soya','Sardina','Sopa de pasta','Sopa de arroz','Vinagre','Avena','Granola','Cereales','Mermelada','Nutella'],
    'Panadería': ['Bagel','Bolillo','Baguette','Croissant','Galletas de avena','Galletas saladas','Muffin','Pan blanco','Pan integral','Pan multigrano','Pan pita','Tortillas','Waffles','Donas','Conchas'],
    'Bebidas': ['Agua mineral','Agua natural','Café molido','Café soluble','Cerveza','Chocolate en polvo','Jugo de manzana','Jugo de naranja','Leche de almendras','Leche de soya','Refresco','Té verde','Té negro','Vino blanco','Vino tinto','Whisky','Vodka','Tequila','Mezcal'],
    'Limpieza': ['Cloro','Desengrasante','Detergente en polvo','Detergente líquido','Escoba','Esponja','Jabón de trastes','Jerga','Limpiador de baño','Limpiador multiusos','Papel de cocina','Suavitel','Bolsas de basura','Trapeador','Aromatizante','Raid'],
    'Higiene personal': ['Acondicionador','Bloqueador solar','Cepillo de dientes','Crema corporal','Desodorante','Enjuague bucal','Gel para cabello','Hilo dental','Jabón de baño','Papel higiénico','Pasta dental','Rastrillos','Shampoo','Tampones','Toallas sanitarias'],
    'Congelados': ['Elote congelado','Helado','Mezcla de vegetales','Nuggets de pollo','Papa a la francesa','Pizza congelada','Pollo empanizado','Waffles congelados'],
    'Snacks y dulces': ['Cacahuates','Chicles','Chocolates','Doritos','Gomitas','Palomitas de microondas','Papas fritas','Pistaches','Pretzels'],
    'Artículos de cocina': ['Bolsas de basura','Cubiertos desechables','Papel aluminio','Papel para hornear','Platos desechables','Servilletas','Vasos desechables'],
    'Bebés': ['Biberón','Leche de fórmula','Pañales','Pañitos húmedos','Papilla de frutas','Papilla de verduras','Shampoo para bebé'],
    'Mascotas': ['Alimento para gato','Alimento para perro','Arena para gato','Galletas para perro','Shampoo para mascotas'],
    'Farmacia básica': ['Alcohol','Agua oxigenada','Aspirina','Ibuprofeno','Paracetamol','Suero oral','Vitamina C'],
  },
  en: {
    'Dairy': ['Cream','Sour cream','Butter','Unsalted butter','Margarine','Condensed milk','Skim milk','Whole milk','Evaporated milk','Lactose-free milk','Cheddar cheese','Cottage cheese','Cream cheese','Mozzarella','Parmesan','Ricotta','Gouda','Brie','Greek yogurt','Plain yogurt','Drinkable yogurt','Low-fat yogurt','Whipping cream','Almond milk'],
    'Meat & deli': ['Beef steak','Ground beef','Beef ribs','Pork chop','Pork loin','Bacon','Ham','Salami','Pepperoni','Mortadella','Whole chicken','Chicken breast','Chicken thigh','Turkey sausage','Sausage','Canned tuna','Shrimp','Fish fillet','Seafood'],
    'Fruits & vegetables': ['Avocado','Garlic','Celery','Blueberries','Beets','Broccoli','Zucchini','Pumpkin','Onion','Red onion','Green onion','Bell pepper','Jalapeño','Cauliflower','Peach','Green beans','Corn','Asparagus','Spinach','Strawberry','Pomegranate','Figs','Mushrooms','Tomato','Kiwi','Lettuce','Lemon','Mandarin','Mango','Apple','Melon','Orange','Potato','Papaya','Cucumber','Pear','Pineapple','Banana','Watermelon','Grapes','Carrot','Sweet potato'],
    'Groceries': ['Oil','Olive oil','White rice','Brown rice','Canned tuna','Sugar','Cinnamon','Chocolate','Chicken broth','Peanut butter','Black beans','Lentils','Gelatin','Flour','Ketchup','Cornstarch','Honey','Mustard','Pasta','Black pepper','Salt','Soy sauce','Hot sauce','Sardines','Oatmeal','Granola','Cereal','Jam','Nutella'],
    'Bakery': ['Bagel','Baguette','Croissant','Oatmeal cookies','Crackers','Muffin','White bread','Whole wheat bread','Multigrain bread','Pita bread','Waffles','Donuts','Tortillas'],
    'Beverages': ['Sparkling water','Water','Ground coffee','Instant coffee','Beer','Hot chocolate powder','Apple juice','Orange juice','Almond milk','Soy milk','Soda','Green tea','Black tea','White wine','Red wine','Whiskey','Vodka'],
    'Cleaning': ['Bleach','Degreaser','Laundry powder','Liquid detergent','Broom','Sponge','Dish soap','Mop','Bathroom cleaner','All-purpose cleaner','Paper towels','Fabric softener','Trash bags','Air freshener','Insect repellent'],
    'Personal care': ['Conditioner','Sunscreen','Toothbrush','Body lotion','Deodorant','Mouthwash','Hair gel','Dental floss','Soap','Toilet paper','Toothpaste','Razors','Shampoo','Tampons','Sanitary pads'],
    'Frozen': ['Frozen corn','Ice cream','Mixed vegetables','Chicken nuggets','French fries','Frozen pizza','Breaded chicken','Frozen waffles'],
    'Snacks & sweets': ['Peanuts','Gum','Chocolate','Chips','Gummies','Popcorn','Potato chips','Pistachios','Pretzels'],
    'Kitchen supplies': ['Trash bags','Disposable cutlery','Aluminum foil','Parchment paper','Disposable plates','Napkins','Disposable cups'],
    'Baby': ['Baby bottle','Formula','Diapers','Baby wipes','Fruit puree','Vegetable puree','Baby shampoo'],
    'Pets': ['Cat food','Dog food','Cat litter','Dog treats','Pet shampoo'],
    'Basic pharmacy': ['Alcohol','Hydrogen peroxide','Aspirin','Ibuprofen','Acetaminophen','Oral rehydration salts','Vitamin C'],
  },
  fr: {
    'Produits laitiers': ['Crème fraîche','Crème sure','Beurre','Beurre sans sel','Margarine','Lait concentré','Lait écrémé','Lait entier','Lait évaporé','Lait sans lactose','Fromage cheddar','Fromage cottage','Fromage à la crème','Mozzarella','Parmesan','Ricotta','Gouda','Brie','Yaourt grec','Yaourt nature','Yaourt à boire','Crème fouettée','Lait d\'amande'],
    'Viandes et charcuterie': ['Steak de bœuf','Bœuf haché','Côtes de bœuf','Côtelette de porc','Filet de porc','Bacon','Jambon','Salami','Pepperoni','Mortadelle','Poulet entier','Blanc de poulet','Cuisse de poulet','Saucisse de dinde','Saucisse','Thon en boîte','Crevettes','Filet de poisson','Fruits de mer'],
    'Fruits et légumes': ['Avocat','Ail','Céleri','Myrtilles','Betterave','Brocoli','Courgette','Citrouille','Oignon','Oignon rouge','Ciboulette','Poivron','Jalapeño','Chou-fleur','Pêche','Haricots verts','Maïs','Asperges','Épinards','Fraise','Grenade','Figues','Champignons','Tomate','Kiwi','Laitue','Citron','Mandarine','Mangue','Pomme','Melon','Orange','Pomme de terre','Papaye','Concombre','Poire','Ananas','Banane','Pastèque','Raisins','Carotte','Patate douce'],
    'Épicerie': ['Huile','Huile d\'olive','Riz blanc','Riz complet','Thon en boîte','Sucre','Cannelle','Chocolat','Bouillon de poulet','Beurre de cacahuète','Haricots noirs','Lentilles','Gélatine','Farine','Ketchup','Maïzena','Miel','Moutarde','Pâtes','Poivre noir','Sel','Sauce soja','Sauce piquante','Sardines','Flocons d\'avoine','Granola','Céréales','Confiture','Nutella'],
    'Boulangerie': ['Bagel','Baguette','Croissant','Biscuits à l\'avoine','Crackers','Muffin','Pain blanc','Pain complet','Pain multigrain','Pain pita','Gaufres','Beignets','Tortillas'],
    'Boissons': ['Eau pétillante','Eau plate','Café moulu','Café soluble','Bière','Chocolat chaud en poudre','Jus de pomme','Jus d\'orange','Lait d\'amande','Lait de soja','Soda','Thé vert','Thé noir','Vin blanc','Vin rouge','Whisky','Vodka'],
    'Nettoyage': ['Eau de javel','Dégraissant','Lessive en poudre','Lessive liquide','Balai','Éponge','Liquide vaisselle','Serpillière','Nettoyant salle de bain','Nettoyant multi-usage','Essuie-tout','Adoucissant','Sacs poubelle','Désodorisant','Insecticide'],
    'Hygiène personnelle': ['Après-shampoing','Crème solaire','Brosse à dents','Crème corporelle','Déodorant','Bain de bouche','Gel coiffant','Fil dentaire','Savon','Papier toilette','Dentifrice','Rasoirs','Shampoing','Tampons','Serviettes hygiéniques'],
    'Surgelés': ['Maïs surgelé','Glace','Légumes mélangés','Nuggets de poulet','Frites','Pizza surgelée','Poulet pané','Gaufres surgelées'],
    'Snacks et confiseries': ['Cacahuètes','Chewing-gum','Chocolat','Chips','Bonbons gélifiés','Popcorn','Chips de pommes de terre','Pistaches','Bretzels'],
    'Articles de cuisine': ['Sacs poubelle','Couverts jetables','Papier aluminium','Papier cuisson','Assiettes jetables','Serviettes','Gobelets jetables'],
    'Bébé': ['Biberon','Lait maternisé','Couches','Lingettes bébé','Purée de fruits','Purée de légumes','Shampooing bébé'],
    'Animaux': ['Nourriture pour chat','Nourriture pour chien','Litière pour chat','Friandises pour chien','Shampooing pour animaux'],
    'Pharmacie de base': ['Alcool','Eau oxygénée','Aspirine','Ibuprofène','Paracétamol','Sels de réhydratation','Vitamine C'],
  },
  de: {
    'Milchprodukte': ['Sahne','Saure Sahne','Butter','Ungesalzene Butter','Margarine','Kondensmilch','Magermilch','Vollmilch','Verdampfte Milch','Laktosefreie Milch','Cheddar','Hüttenkäse','Frischkäse','Mozzarella','Parmesan','Ricotta','Gouda','Brie','Griechischer Joghurt','Naturjoghurt','Trinkjoghurt','Schlagsahne','Mandelmilch'],
    'Fleisch & Wurst': ['Rindersteak','Rinderhackfleisch','Rinderrippen','Schweinekotelett','Schweinefilet','Speck','Schinken','Salami','Pepperoni','Mortadella','Ganzes Hähnchen','Hähnchenbrust','Hähnchenschenkel','Putenwurst','Bratwurst','Thunfischkonserve','Garnelen','Fischfilet','Meeresfrüchte'],
    'Obst & Gemüse': ['Avocado','Knoblauch','Sellerie','Blaubeeren','Rote Bete','Brokkoli','Zucchini','Kürbis','Zwiebel','Rote Zwiebel','Frühlingszwiebel','Paprika','Jalapeño','Blumenkohl','Pfirsich','Grüne Bohnen','Mais','Spargel','Spinat','Erdbeere','Granatapfel','Feigen','Champignons','Tomate','Kiwi','Salat','Zitrone','Mandarine','Mango','Apfel','Melone','Orange','Kartoffel','Papaya','Gurke','Birne','Ananas','Banane','Wassermelone','Weintrauben','Karotte','Süßkartoffel'],
    'Lebensmittel': ['Öl','Olivenöl','Weißer Reis','Brauner Reis','Thunfisch','Zucker','Zimt','Schokolade','Hühnerbrühe','Erdnussbutter','Schwarze Bohnen','Linsen','Gelatine','Mehl','Ketchup','Speisestärke','Honig','Senf','Nudeln','Schwarzer Pfeffer','Salz','Sojasoße','Scharfe Soße','Sardinen','Haferflocken','Granola','Müsli','Marmelade','Nutella'],
    'Backwaren': ['Bagel','Baguette','Croissant','Haferkekse','Cracker','Muffin','Weißbrot','Vollkornbrot','Mehrkornbrot','Pitabrot','Waffeln','Donuts','Tortillas'],
    'Getränke': ['Mineralwasser','Wasser','Gemahlener Kaffee','Instantkaffee','Bier','Kakao','Apfelsaft','Orangensaft','Mandelmilch','Sojamilch','Limonade','Grüner Tee','Schwarzer Tee','Weißwein','Rotwein','Whisky','Wodka'],
    'Reinigung': ['Bleichmittel','Entfetter','Waschpulver','Flüssigwaschmittel','Besen','Schwamm','Spülmittel','Wischmopp','Badreiniger','Allzweckreiniger','Küchenrolle','Weichspüler','Müllbeutel','Lufterfrischer','Insektenspray'],
    'Körperpflege': ['Haarspülung','Sonnencreme','Zahnbürste','Körperlotion','Deodorant','Mundwasser','Haargel','Zahnseide','Seife','Toilettenpapier','Zahnpasta','Rasierklingen','Shampoo','Tampons','Damenbinden'],
    'Tiefkühlkost': ['Tiefkühlmais','Eis','Gemüsemischung','Chicken Nuggets','Pommes frites','Tiefkühlpizza','Paniertes Hähnchen','Tiefkühlwaffeln'],
    'Snacks & Süßigkeiten': ['Erdnüsse','Kaugummi','Schokolade','Chips','Gummibärchen','Popcorn','Kartoffelchips','Pistazien','Brezeln'],
    'Küchenartikel': ['Müllbeutel','Einwegbesteck','Alufolie','Backpapier','Einwegteller','Servietten','Einwegbecher'],
    'Baby': ['Babyflasche','Säuglingsnahrung','Windeln','Feuchttücher','Fruchtbrei','Gemüsebrei','Babyshampoo'],
    'Haustiere': ['Katzenfutter','Hundefutter','Katzenstreu','Hundekekse','Tiershampoo'],
    'Hausapotheke': ['Alkohol','Wasserstoffperoxid','Aspirin','Ibuprofen','Paracetamol','Elektrolytlösung','Vitamin C'],
  },
  it: {
    'Latticini': ['Panna','Panna acida','Burro','Burro non salato','Margarina','Latte condensato','Latte scremato','Latte intero','Latte evaporato','Latte senza lattosio','Formaggio cheddar','Ricotta','Formaggio cremoso','Mozzarella','Parmigiano','Gorgonzola','Gouda','Brie','Yogurt greco','Yogurt naturale','Yogurt da bere','Panna da montare','Latte di mandorle'],
    'Carne e salumi': ['Bistecca di manzo','Carne macinata','Costine di manzo','Braciola di maiale','Filetto di maiale','Pancetta','Prosciutto cotto','Salame','Pepperoni','Mortadella','Pollo intero','Petto di pollo','Coscia di pollo','Salsiccia di tacchino','Salsiccia','Tonno in scatola','Gamberetti','Filetto di pesce','Frutti di mare'],
    'Frutta e verdura': ['Avocado','Aglio','Sedano','Mirtilli','Barbabietola','Broccoli','Zucchini','Zucca','Cipolla','Cipolla rossa','Cipollotto','Peperone','Jalapeño','Cavolfiore','Pesca','Fagiolini','Mais','Asparagi','Spinaci','Fragola','Melograno','Fichi','Funghi','Pomodoro','Kiwi','Lattuga','Limone','Mandarino','Mango','Mela','Melone','Arancia','Patata','Papaya','Cetriolo','Pera','Ananas','Banana','Anguria','Uva','Carota','Patata dolce'],
    'Alimentari': ['Olio','Olio d\'oliva','Riso bianco','Riso integrale','Tonno','Zucchero','Cannella','Cioccolato','Brodo di pollo','Burro di arachidi','Fagioli neri','Lenticchie','Gelatina','Farina','Ketchup','Amido di mais','Miele','Senape','Pasta','Pepe nero','Sale','Salsa di soia','Salsa piccante','Sardine','Fiocchi d\'avena','Granola','Cereali','Marmellata','Nutella'],
    'Panetteria': ['Bagel','Baguette','Croissant','Biscotti d\'avena','Cracker','Muffin','Pane bianco','Pane integrale','Pane multicereali','Pane pita','Waffle','Ciambelle','Tortillas'],
    'Bevande': ['Acqua frizzante','Acqua naturale','Caffè macinato','Caffè solubile','Birra','Cioccolata in polvere','Succo di mela','Succo d\'arancia','Latte di mandorle','Latte di soia','Bibita','Tè verde','Tè nero','Vino bianco','Vino rosso','Whisky','Vodka'],
    'Pulizia': ['Candeggina','Sgrassatore','Detersivo in polvere','Detersivo liquido','Scopa','Spugna','Detersivo piatti','Mocio','Detergente bagno','Detergente multiuso','Carta da cucina','Ammorbidente','Sacchi spazzatura','Deodorante ambiente','Insetticida'],
    'Igiene personale': ['Balsamo','Crema solare','Spazzolino','Crema corpo','Deodorante','Collutorio','Gel per capelli','Filo interdentale','Sapone','Carta igienica','Dentifricio','Rasoi','Shampoo','Tamponi','Assorbenti'],
    'Surgelati': ['Mais surgelato','Gelato','Verdure miste','Nuggets di pollo','Patatine fritte','Pizza surgelata','Pollo impanato','Waffle surgelati'],
    'Snack e dolci': ['Arachidi','Gomme da masticare','Cioccolato','Patatine','Caramelle gommose','Popcorn','Chips','Pistacchi','Pretzel'],
    'Articoli da cucina': ['Sacchi spazzatura','Posate usa e getta','Carta stagnola','Carta da forno','Piatti usa e getta','Tovaglioli','Bicchieri usa e getta'],
    'Neonati': ['Biberon','Latte artificiale','Pannolini','Salviettine umidificate','Purea di frutta','Purea di verdure','Shampoo per bambini'],
    'Animali': ['Cibo per gatti','Cibo per cani','Lettiera per gatti','Biscotti per cani','Shampoo per animali'],
    'Farmacia base': ['Alcol','Acqua ossigenata','Aspirina','Ibuprofene','Paracetamolo','Sali da reidratazione','Vitamina C'],
  },
  pt: {
    'Laticínios': ['Creme de leite','Creme azedo','Manteiga','Manteiga sem sal','Margarina','Leite condensado','Leite desnatado','Leite integral','Leite evaporado','Leite sem lactose','Queijo cheddar','Queijo cottage','Cream cheese','Mozzarella','Parmesão','Ricota','Gouda','Brie','Iogurte grego','Iogurte natural','Iogurte para beber','Creme de leite fresco','Leite de amêndoas'],
    'Carnes e frios': ['Bife','Carne moída','Costela bovina','Costeleta de porco','Filé de porco','Bacon','Presunto','Salame','Pepperoni','Mortadela','Frango inteiro','Peito de frango','Coxa de frango','Linguiça de peru','Linguiça','Atum em lata','Camarão','Filé de peixe','Frutos do mar'],
    'Frutas e legumes': ['Abacate','Alho','Aipo','Mirtilos','Beterraba','Brócolis','Abobrinha','Abóbora','Cebola','Cebola roxa','Cebolinha','Pimentão','Jalapeño','Couve-flor','Pêssego','Vagem','Milho','Aspargo','Espinafre','Morango','Romã','Figo','Cogumelos','Tomate','Kiwi','Alface','Limão','Tangerina','Manga','Maçã','Melão','Laranja','Batata','Mamão','Pepino','Pera','Abacaxi','Banana','Melancia','Uva','Cenoura','Batata-doce'],
    'Mercearia': ['Óleo','Azeite','Arroz branco','Arroz integral','Atum','Açúcar','Canela','Chocolate','Caldo de frango','Manteiga de amendoim','Feijão preto','Lentilha','Gelatina','Farinha','Ketchup','Amido de milho','Mel','Mostarda','Macarrão','Pimenta preta','Sal','Molho de soja','Molho picante','Sardinha','Aveia','Granola','Cereal','Geleia','Nutella'],
    'Padaria': ['Bagel','Baguete','Croissant','Biscoito de aveia','Biscoito salgado','Muffin','Pão branco','Pão integral','Pão multigrãos','Pão pita','Waffle','Rosquinha','Tortilha'],
    'Bebidas': ['Água com gás','Água mineral','Café moído','Café solúvel','Cerveja','Chocolate em pó','Suco de maçã','Suco de laranja','Leite de amêndoas','Leite de soja','Refrigerante','Chá verde','Chá preto','Vinho branco','Vinho tinto','Whisky','Vodka'],
    'Limpeza': ['Água sanitária','Desengordurante','Sabão em pó','Detergente líquido','Vassoura','Esponja','Detergente louça','Mop','Limpador de banheiro','Limpador multiuso','Papel toalha','Amaciante','Sacos de lixo','Aromatizante','Inseticida'],
    'Higiene pessoal': ['Condicionador','Protetor solar','Escova de dentes','Creme corporal','Desodorante','Enxaguante bucal','Gel para cabelo','Fio dental','Sabonete','Papel higiênico','Creme dental','Barbeador','Shampoo','Absorvente interno','Absorvente'],
    'Congelados': ['Milho congelado','Sorvete','Legumes mistos','Nuggets de frango','Batata frita','Pizza congelada','Frango empanado','Waffle congelado'],
    'Snacks e doces': ['Amendoim','Chiclete','Chocolate','Salgadinho','Gelatina','Pipoca','Batata frita','Pistache','Pretzel'],
    'Artigos de cozinha': ['Sacos de lixo','Talheres descartáveis','Papel alumínio','Papel manteiga','Pratos descartáveis','Guardanapos','Copos descartáveis'],
    'Bebê': ['Mamadeira','Fórmula infantil','Fraldas','Lenços umedecidos','Papinha de frutas','Papinha de legumes','Shampoo infantil'],
    'Pets': ['Ração para gato','Ração para cachorro','Areia para gato','Petisco para cachorro','Shampoo para pets'],
    'Farmácia básica': ['Álcool','Água oxigenada','Aspirina','Ibuprofeno','Paracetamol','Soro oral','Vitamina C'],
  },
  ja: {
    '乳製品': ['生クリーム','サワークリーム','バター','無塩バター','マーガリン','練乳','スキムミルク','全乳','エバミルク','乳糖フリーミルク','チェダーチーズ','カッテージチーズ','クリームチーズ','モッツァレラ','パルメザン','リコッタ','ゴーダ','ブリー','ギリシャヨーグルト','プレーンヨーグルト','飲むヨーグルト','ホイップクリーム','アーモンドミルク'],
    '肉・加工肉': ['牛ステーキ','ひき肉','牛リブ','豚カツレツ','豚ヒレ肉','ベーコン','ハム','サラミ','ペパロニ','モルタデッラ','丸鶏','鶏胸肉','鶏もも肉','七面鳥ソーセージ','ソーセージ','ツナ缶','エビ','魚のフィレ','シーフード'],
    '果物・野菜': ['アボカド','にんにく','セロリ','ブルーベリー','ビーツ','ブロッコリー','ズッキーニ','かぼちゃ','玉ねぎ','赤玉ねぎ','ねぎ','ピーマン','ハラペーニョ','カリフラワー','桃','さやいんげん','とうもろこし','アスパラガス','ほうれん草','いちご','ざくろ','いちじく','きのこ','トマト','キウイ','レタス','レモン','みかん','マンゴー','りんご','メロン','オレンジ','じゃがいも','パパイヤ','きゅうり','梨','パイナップル','バナナ','スイカ','ぶどう','にんじん','さつまいも'],
    '食料品': ['油','オリーブオイル','白米','玄米','ツナ','砂糖','シナモン','チョコレート','チキンブロス','ピーナッツバター','黒豆','レンズ豆','ゼラチン','小麦粉','ケチャップ','コーンスターチ','はちみつ','マスタード','パスタ','黒コショウ','塩','醤油','ホットソース','いわし','オートミール','グラノーラ','シリアル','ジャム','ヌテラ'],
    'ベーカリー': ['ベーグル','バゲット','クロワッサン','オートミールクッキー','クラッカー','マフィン','食パン','全粒粉パン','マルチグレインパン','ピタパン','ワッフル','ドーナツ','トルティーヤ'],
    '飲み物': ['炭酸水','ミネラルウォーター','挽きコーヒー','インスタントコーヒー','ビール','ココアパウダー','アップルジュース','オレンジジュース','アーモンドミルク','豆乳','ソーダ','緑茶','紅茶','白ワイン','赤ワイン','ウイスキー','ウォッカ'],
    '洗剤・清掃': ['漂白剤','油汚れ落とし','洗濯粉','液体洗剤','ほうき','スポンジ','食器用洗剤','モップ','バスルームクリーナー','多目的クリーナー','キッチンペーパー','柔軟剤','ゴミ袋','消臭剤','殺虫剤'],
    'パーソナルケア': ['コンディショナー','日焼け止め','歯ブラシ','ボディクリーム','デオドラント','マウスウォッシュ','ヘアジェル','デンタルフロス','石鹸','トイレットペーパー','歯磨き粉','カミソリ','シャンプー','タンポン','生理用ナプキン'],
    '冷凍食品': ['冷凍コーン','アイスクリーム','ミックス野菜','チキンナゲット','フライドポテト','冷凍ピザ','フライドチキン','冷凍ワッフル'],
    'お菓子': ['ピーナッツ','ガム','チョコレート','ポテトチップス','グミ','ポップコーン','スナック菓子','ピスタチオ','プレッツェル'],
    'キッチン用品': ['ゴミ袋','使い捨てカトラリー','アルミホイル','クッキングシート','使い捨て皿','ナプキン','使い捨てカップ'],
    '赤ちゃん用品': ['哺乳瓶','粉ミルク','おむつ','おしりふき','果物ピューレ','野菜ピューレ','ベビーシャンプー'],
    'ペット用品': ['猫のえさ','犬のえさ','猫砂','犬のおやつ','ペット用シャンプー'],
    '常備薬': ['アルコール','過酸化水素','アスピリン','イブプロフェン','アセトアミノフェン','経口補水液','ビタミンC'],
  },
  zh: {
    '乳制品': ['淡奶油','酸奶油','黄油','无盐黄油','人造黄油','炼乳','脱脂牛奶','全脂牛奶','蒸发奶','无乳糖牛奶','切达奶酪','农家奶酪','奶油奶酪','马苏里拉奶酪','帕玛森奶酪','瑞可达奶酪','高达奶酪','布里奶酪','希腊酸奶','原味酸奶','饮用酸奶','鲜奶油','杏仁奶'],
    '肉类和熟食': ['牛排','碎牛肉','牛肋骨','猪排','猪里脊','培根','火腿','萨拉米','意大利辣香肠','博洛尼亚香肠','整鸡','鸡胸肉','鸡腿肉','火鸡香肠','香肠','金枪鱼罐头','虾','鱼排','海鲜'],
    '水果和蔬菜': ['牛油果','大蒜','芹菜','蓝莓','甜菜','西兰花','西葫芦','南瓜','洋葱','红洋葱','葱','彩椒','墨西哥辣椒','花椰菜','桃子','四季豆','玉米','芦笋','菠菜','草莓','石榴','无花果','蘑菇','番茄','猕猴桃','生菜','柠檬','柑橘','芒果','苹果','哈密瓜','橙子','土豆','木瓜','黄瓜','梨','菠萝','香蕉','西瓜','葡萄','胡萝卜','红薯'],
    '杂货': ['食用油','橄榄油','白米','糙米','金枪鱼','糖','肉桂','巧克力','鸡汤','花生酱','黑豆','扁豆','明胶','面粉','番茄酱','玉米淀粉','蜂蜜','芥末','意大利面','黑胡椒','盐','酱油','辣酱','沙丁鱼','燕麦片','格兰诺拉麦片','麦片','果酱','能多益'],
    '烘焙食品': ['百吉饼','法棍','可颂','燕麦饼干','苏打饼干','松饼','白面包','全麦面包','杂粮面包','皮塔饼','华夫饼','甜甜圈','玉米饼'],
    '饮料': ['气泡水','矿泉水','研磨咖啡','速溶咖啡','啤酒','可可粉','苹果汁','橙汁','杏仁奶','豆奶','汽水','绿茶','红茶','白葡萄酒','红葡萄酒','威士忌','伏特加'],
    '清洁用品': ['漂白剂','去污剂','洗衣粉','液体洗涤剂','扫帚','海绵','洗碗精','拖把','浴室清洁剂','多用途清洁剂','厨房纸巾','柔顺剂','垃圾袋','空气清新剂','杀虫剂'],
    '个人护理': ['护发素','防晒霜','牙刷','身体乳','除臭剂','漱口水','发胶','牙线','香皂','卫生纸','牙膏','剃须刀','洗发水','卫生棉条','卫生巾'],
    '冷冻食品': ['冷冻玉米','冰淇淋','混合蔬菜','鸡块','薯条','冷冻披萨','炸鸡','冷冻华夫饼'],
    '零食和糖果': ['花生','口香糖','巧克力','薯片','软糖','爆米花','薯片','开心果','椒盐卷饼'],
    '厨房用品': ['垃圾袋','一次性餐具','铝箔纸','烘焙纸','一次性盘子','餐巾纸','一次性杯子'],
    '婴儿用品': ['奶瓶','婴儿配方奶粉','纸尿裤','湿纸巾','水果泥','蔬菜泥','婴儿洗发水'],
    '宠物用品': ['猫粮','狗粮','猫砂','狗零食','宠物洗发水'],
    '基本药品': ['酒精','双氧水','阿司匹林','布洛芬','对乙酰氨基酚','口服补液盐','维生素C'],
  },
}

export const DEP_ORDER_BY_LANG = {
  es: ['Lácteos','Carnes y embutidos','Frutas y verduras','Abarrotes','Panadería','Bebidas','Limpieza','Higiene personal','Congelados','Snacks y dulces','Artículos de cocina','Bebés','Mascotas','Farmacia básica'],
  en: ['Dairy','Meat & deli','Fruits & vegetables','Groceries','Bakery','Beverages','Cleaning','Personal care','Frozen','Snacks & sweets','Kitchen supplies','Baby','Pets','Basic pharmacy'],
  fr: ['Produits laitiers','Viandes et charcuterie','Fruits et légumes','Épicerie','Boulangerie','Boissons','Nettoyage','Hygiène personnelle','Surgelés','Snacks et confiseries','Articles de cuisine','Bébé','Animaux','Pharmacie de base'],
  de: ['Milchprodukte','Fleisch & Wurst','Obst & Gemüse','Lebensmittel','Backwaren','Getränke','Reinigung','Körperpflege','Tiefkühlkost','Snacks & Süßigkeiten','Küchenartikel','Baby','Haustiere','Hausapotheke'],
  it: ['Latticini','Carne e salumi','Frutta e verdura','Alimentari','Panetteria','Bevande','Pulizia','Igiene personale','Surgelati','Snack e dolci','Articoli da cucina','Neonati','Animali','Farmacia base'],
  pt: ['Laticínios','Carnes e frios','Frutas e legumes','Mercearia','Padaria','Bebidas','Limpeza','Higiene pessoal','Congelados','Snacks e doces','Artigos de cozinha','Bebê','Pets','Farmácia básica'],
  ja: ['乳製品','肉・加工肉','果物・野菜','食料品','ベーカリー','飲み物','洗剤・清掃','パーソナルケア','冷凍食品','お菓子','キッチン用品','赤ちゃん用品','ペット用品','常備薬'],
  zh: ['乳制品','肉类和熟食','水果和蔬菜','杂货','烘焙食品','饮料','清洁用品','个人护理','冷冻食品','零食和糖果','厨房用品','婴儿用品','宠物用品','基本药品'],
}
