export const TEXTOS = {
  es: {
    // Auth
    iniciar:'Iniciar sesión', registrar:'Registrarse', correo:'Correo electrónico',
    contrasena:'Contraseña', entrar:'Entrar', crear:'Crear cuenta',
    oCon:'o continúa con', google:'Continuar con Google', cargando:'Cargando...',
    errorCred:'Correo o contraseña incorrectos', errorCampos:'Escribe tu correo y contraseña',
    errorGoogle:'Error al iniciar con Google', eligeIdioma:'Elige tu idioma',
    slogan:'Sincroniza tu mundo',
    // Nav
    inicio:'Inicio', perfil:'Perfil', super2:'Súper', compartir:'Compartir',
    // Home
    hola:'Hola', queOrganizar:'¿Qué quieres organizar hoy?',
    pendientesHoy:'pendientes para hoy', pendientes:'Pendientes hoy', completadas:'Completadas',
    misModulos:'MIS MÓDULOS',
    pendientesPizarron:'Pendientes hoy por pizarrón', completadasPizarron:'Completadas hoy por pizarrón',
    sinTareas:'Sin tareas para mostrar',
    miAgenda:'Mi Agenda', miAgendaDesc:'Todos tus pendientes en un solo lugar',
    // Pizarron
    pizarron:'Pizarrón', pizarronDesc:'Calendario colaborativo',
    misPizarrones:'Mis Pizarrones', personal:'Personal', soloYo:'Solo yo',
    miembros:'Miembros', administrador:'Administrador', miembro:'Miembro',
    nuevoPizarron:'Nuevo pizarrón compartido', nuevoGrupo:'Nuevo grupo',
    nombreGrupo:'Nombre del grupo', crearGrupo:'Crear', cancelar:'Cancelar',
    invitarGrupo:'Invitar al grupo', invitandoGrupo:'Enviando invitación...',
    linkUnico:'Cada link funciona una sola vez. Puedes generar los que necesites.',
    salirGrupo:'Salir del grupo', eliminarGrupo:'Eliminar grupo',
    confirmarSalir:'¿Salir del grupo?', confirmarSalirMsg:'Ya no verás el pizarrón de este grupo.',
    confirmarEliminarGrupo:'¿Eliminar grupo?', confirmarEliminarGrupoMsg:'Se eliminará para todos y se perderán las anotaciones.',
    quitarMiembro:'Quitar', confirmarQuitar:'¿Quitar a', confirmarQuitarMsg:'Se le eliminará del grupo.',
    pendientesLabel:'Pendientes', atendidasLabel:'Atendidas',
    nuevaAnotacion:'Nueva anotación...', repetir:'Repetir',
    cambiarFecha:'Cambiar fecha', repetirFechas:'Repetir en más fechas',
    moverA:'Toca el día al que quieres mover esta anotación',
    copiarEn:'Toca los días donde quieres copiar esta anotación',
    fechasSel:'fecha(s) seleccionada(s)',
    sinAnotaciones:'No hay anotaciones para este día',
    confirmarEliminar:'¿Eliminar esta tarea?', soloEsta:'Solo esta fecha',
    todasRepeticiones:'Todas las repeticiones', eliminar:'Eliminar',
    queDeseasEliminar:'¿Qué deseas eliminar?',
    bienvenidoTitulo:'¡Bienvenido a Syng!',
    bienvenidoMsg:'Estás explorando como invitado. Para guardar tus tareas, colaborar y tener tu propio Syng, inicia sesión gratis.',
    iniciarSesion:'Iniciar sesión', seguirExplorando:'Seguir explorando',
    cargandoPizarron:'Cargando pizarrón...',
    buscarGrupo:'Buscar grupo...', nuevoGrupoOpcion:'Nuevo grupo',
    moviendo:'moviendo...', reordenando:'reordenando...',
    masDe:'más',
    // Super
    super:'Lista del Súper', superDesc:'Compras con catálogo',
    listSuper:'Lista del Súper', productos:'productos',
    nuevoGrupoSuper:'+ Nuevo grupo', catalogo:'Catálogo', miLista:'Mi lista',
    buscarCatalogo:'Buscar en catálogo...', buscarLista:'Buscar en mi lista...',
    sinResultados:'Sin resultados para', agregarProd:'+ agregar',
    tocaCirculo:'Toca el círculo o el texto para marcar como jalado',
    seleccionar:'Seleccionar', seleccionados:'seleccionado(s)',
    borrarMarcados:'Borrar marcados', borrarLista:'Borrar lista',
    misGrupos:'Mis grupos', integrantes:'integrantes', cerrar:'Cerrar',
    nombreGrupoPlaceholder:'Nombre del grupo (ej. Amigos)',
    nombreProd:'Nombre del producto', agregarA:'Agregar a',
    editarProd:'Editar producto', nombre:'Nombre', guardar:'Guardar',
    confirmarEliminarProd:'Este producto se eliminará de tu catálogo personal.',
    confirmarEliminarLista:'Se quitarán de tu lista actual.',
    confirmarBorrarMarcados:'¿Borrar marcados?',
    confirmarBorrarLista:'Se eliminarán todos los productos de tu lista actual.',
    seleccionarProd:'Selecciona productos del catálogo para armar tu lista',
    // Perfil
    apariencia:'Apariencia', modoOscuro:'Modo oscuro', modoClaro:'Modo claro',
    idioma:'Idioma', privacidad:'Privacidad', cerrarSesion:'Cerrar sesión',
    miPerfil:'Mi perfil', configuracion:'Configuración',
    instalarSyng:'Instalar Syng', instalarDesc:'Agrega la app a tu pantalla de inicio',
    instalarTitulo:'¿Instalar Syng?',
    instalarIos:'En Safari: toca Compartir y selecciona Agregar a pantalla de inicio',
    instalarAndroid:'Accede más rápido desde tu pantalla de inicio, sin abrir el navegador',
    ahoraNO:'Ahora no', compartirSyng:'Compartir Syng',
    version:'Syng v2.61 — Hecho con amor 🖤',
    // Sinyi
    vozVoz:'es-MX',
    sinyiSaludo:'¿En qué te puedo ayudar?', sinyiDime:'Dime, ¿en qué te ayudo?',
    sinyiError:'No te escuché bien. ¿Puedes repetirlo?',
    sinyiSistema:'Eres Sinyi, asistente de voz de la app Syng. Eres una mujer inteligente y cálida. Responde siempre en español mexicano, muy breve, máximo 2 oraciones. No digas que eres IA.',
    // Mi Agenda
    agendaTitulo:'Mi Agenda', agendaSinPendientes:'Sin pendientes este día',
    agendaGuardarEn:'Guardar en', agendaPizarron:'¿En qué pizarrón?',
    agendaNuevaTarea:'¿Qué tienes pendiente?', agendaAgregar:'+ agregar',
    agendaGuardar:'Guardar', agendaCancelar:'Cancelar', agendaEliminar:'Eliminar',
    agendaGuardarCambios:'Guardar cambios', agendaCambiarFecha:'Cambiar fecha',
    agendaRepetirFechas:'Repetir en más fechas',
    agendaConfirmarEliminar:'¿Eliminar esta tarea?', agendaSi:'Sí, eliminar',
    agendaMoverA:'Toca el día al que quieres mover esta tarea',
    agendaCopiarEn:'Toca los días donde quieres copiar esta tarea',
    agendaFechasSel:'fecha(s) seleccionada(s)', agendaRepetir:'Repetir',
    // Meses y dias
    meses:['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'],
    mesesCorto:['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic'],
    diasSemana:['Dom','Lun','Mar','Mie','Jue','Vie','Sab'],
    diasSemanaCorto:['L','M','M','J','V','S','D'],
  },
  en: {
    iniciar:'Sign in', registrar:'Sign up', correo:'Email address',
    contrasena:'Password', entrar:'Sign in', crear:'Create account',
    oCon:'or continue with', google:'Continue with Google', cargando:'Loading...',
    errorCred:'Wrong email or password', errorCampos:'Please enter your email and password',
    errorGoogle:'Error signing in with Google', eligeIdioma:'Choose your language',
    slogan:'Sync your world',
    inicio:'Home', perfil:'Profile', super2:'Super', compartir:'Share',
    hola:'Hello', queOrganizar:'What do you want to organize today?',
    pendientesHoy:'pending for today', pendientes:'Pending today', completadas:'Completed',
    misModulos:'MY MODULES',
    pendientesPizarron:'Pending today by board', completadasPizarron:'Completed today by board',
    sinTareas:'No tasks to show',
    miAgenda:'My Agenda', miAgendaDesc:'All your tasks in one place',
    pizarron:'Board', pizarronDesc:'Collaborative calendar',
    misPizarrones:'My Boards', personal:'Personal', soloYo:'Just me',
    miembros:'Members', administrador:'Admin', miembro:'Member',
    nuevoPizarron:'New shared board', nuevoGrupo:'New group',
    nombreGrupo:'Group name', crearGrupo:'Create', cancelar:'Cancel',
    invitarGrupo:'Invite to group', invitandoGrupo:'Sending invitation...',
    linkUnico:'Each link works once. You can generate as many as you need.',
    salirGrupo:'Leave group', eliminarGrupo:'Delete group',
    confirmarSalir:'Leave group?', confirmarSalirMsg:'You will no longer see this group board.',
    confirmarEliminarGrupo:'Delete group?', confirmarEliminarGrupoMsg:'It will be deleted for everyone and all notes will be lost.',
    quitarMiembro:'Remove', confirmarQuitar:'Remove', confirmarQuitarMsg:'They will be removed from the group.',
    pendientesLabel:'Pending', atendidasLabel:'Done',
    nuevaAnotacion:'New note...', repetir:'Repeat',
    cambiarFecha:'Change date', repetirFechas:'Repeat on more dates',
    moverA:'Tap the day you want to move this note to',
    copiarEn:'Tap the days where you want to copy this note',
    fechasSel:'date(s) selected',
    sinAnotaciones:'No notes for this day',
    confirmarEliminar:'Delete this task?', soloEsta:'Only this date',
    todasRepeticiones:'All repetitions', eliminar:'Delete',
    queDeseasEliminar:'What do you want to delete?',
    bienvenidoTitulo:'Welcome to Syng!',
    bienvenidoMsg:'You are exploring as a guest. Sign in for free to save your tasks and collaborate.',
    iniciarSesion:'Sign in', seguirExplorando:'Keep exploring',
    cargandoPizarron:'Loading board...',
    buscarGrupo:'Search group...', nuevoGrupoOpcion:'New group',
    moviendo:'moving...', reordenando:'reordering...',
    masDe:'more',
    super:'Shopping List', superDesc:'Shopping with catalog',
    listSuper:'Shopping List', productos:'products',
    nuevoGrupoSuper:'+ New group', catalogo:'Catalog', miLista:'My list',
    buscarCatalogo:'Search catalog...', buscarLista:'Search my list...',
    sinResultados:'No results for', agregarProd:'+ add',
    tocaCirculo:'Tap the circle or text to mark as picked',
    seleccionar:'Select', seleccionados:'selected',
    borrarMarcados:'Delete marked', borrarLista:'Clear list',
    misGrupos:'My groups', integrantes:'members', cerrar:'Close',
    nombreGrupoPlaceholder:'Group name (e.g. Friends)',
    nombreProd:'Product name', agregarA:'Add to',
    editarProd:'Edit product', nombre:'Name', guardar:'Save',
    confirmarEliminarProd:'This product will be removed from your personal catalog.',
    confirmarEliminarLista:'They will be removed from your current list.',
    confirmarBorrarMarcados:'Delete marked?',
    confirmarBorrarLista:'All products will be removed from your current list.',
    seleccionarProd:'Select products from the catalog to build your list',
    apariencia:'Appearance', modoOscuro:'Dark mode', modoClaro:'Light mode',
    idioma:'Language', privacidad:'Privacy', cerrarSesion:'Sign out',
    miPerfil:'My profile', configuracion:'Settings',
    instalarSyng:'Install Syng', instalarDesc:'Add the app to your home screen',
    instalarTitulo:'Install Syng?',
    instalarIos:'In Safari: tap Share and select Add to Home Screen',
    instalarAndroid:'Access faster from your home screen without opening the browser',
    ahoraNO:'Not now', compartirSyng:'Share Syng',
    version:'Syng v2.61 — Made with love 🖤',
    vozVoz:'en-US',
    sinyiSaludo:'How can I help you?', sinyiDime:'Tell me, how can I help?',
    sinyiError:"I didn't hear you. Can you repeat that?",
    sinyiSistema:'You are Sinyi, voice assistant of the Syng app. You are an intelligent and warm woman. Always respond in English, very briefly, maximum 2 sentences. Do not say you are AI.',
    agendaTitulo:'My Agenda', agendaSinPendientes:'No tasks this day',
    agendaGuardarEn:'Save to', agendaPizarron:'Which board?',
    agendaNuevaTarea:'What is pending?', agendaAgregar:'+ add',
    agendaGuardar:'Save', agendaCancelar:'Cancel', agendaEliminar:'Delete',
    agendaGuardarCambios:'Save changes', agendaCambiarFecha:'Change date',
    agendaRepetirFechas:'Repeat on more dates',
    agendaConfirmarEliminar:'Delete this task?', agendaSi:'Yes, delete',
    agendaMoverA:'Tap the day to move this task',
    agendaCopiarEn:'Tap days to copy this task',
    agendaFechasSel:'date(s) selected', agendaRepetir:'Repeat',
    meses:['January','February','March','April','May','June','July','August','September','October','November','December'],
    mesesCorto:['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],
    diasSemana:['Sun','Mon','Tue','Wed','Thu','Fri','Sat'],
    diasSemanaCorto:['M','T','W','T','F','S','S'],
  },
  fr: {
    iniciar:'Se connecter', registrar:"S'inscrire", correo:'Adresse e-mail',
    contrasena:'Mot de passe', entrar:'Connexion', crear:'Créer un compte',
    oCon:'ou continuer avec', google:'Continuer avec Google', cargando:'Chargement...',
    errorCred:'E-mail ou mot de passe incorrect', errorCampos:'Veuillez entrer votre e-mail et mot de passe',
    errorGoogle:'Erreur de connexion avec Google', eligeIdioma:'Choisissez votre langue',
    slogan:'Synchronisez votre monde',
    inicio:'Accueil', perfil:'Profil', super2:'Courses', compartir:'Partager',
    hola:'Bonjour', queOrganizar:"Que voulez-vous organiser aujourd'hui?",
    pendientesHoy:"en attente aujourd'hui", pendientes:'En attente', completadas:'Terminées',
    misModulos:'MES MODULES',
    pendientesPizarron:"En attente aujourd'hui par tableau", completadasPizarron:"Terminées aujourd'hui par tableau",
    sinTareas:'Aucune tâche à afficher',
    miAgenda:'Mon Agenda', miAgendaDesc:'Toutes vos tâches en un seul endroit',
    pizarron:'Tableau', pizarronDesc:'Calendrier collaboratif',
    misPizarrones:'Mes Tableaux', personal:'Personnel', soloYo:'Moi seul',
    miembros:'Membres', administrador:'Admin', miembro:'Membre',
    nuevoPizarron:'Nouveau tableau partagé', nuevoGrupo:'Nouveau groupe',
    nombreGrupo:'Nom du groupe', crearGrupo:'Créer', cancelar:'Annuler',
    invitarGrupo:'Inviter au groupe', invitandoGrupo:"Envoi de l'invitation...",
    linkUnico:'Chaque lien fonctionne une seule fois. Vous pouvez en générer autant que nécessaire.',
    salirGrupo:'Quitter le groupe', eliminarGrupo:'Supprimer le groupe',
    confirmarSalir:'Quitter le groupe?', confirmarSalirMsg:'Vous ne verrez plus le tableau de ce groupe.',
    confirmarEliminarGrupo:'Supprimer le groupe?', confirmarEliminarGrupoMsg:'Il sera supprimé pour tous et les notes seront perdues.',
    quitarMiembro:'Retirer', confirmarQuitar:'Retirer', confirmarQuitarMsg:'Il sera retiré du groupe.',
    pendientesLabel:'En attente', atendidasLabel:'Terminées',
    nuevaAnotacion:'Nouvelle note...', repetir:'Répéter',
    cambiarFecha:'Changer la date', repetirFechas:'Répéter sur plus de dates',
    moverA:'Appuyez sur le jour où vous voulez déplacer cette note',
    copiarEn:'Appuyez sur les jours où vous voulez copier cette note',
    fechasSel:'date(s) sélectionnée(s)',
    sinAnotaciones:'Aucune note pour ce jour',
    confirmarEliminar:'Supprimer cette tâche?', soloEsta:'Seulement cette date',
    todasRepeticiones:'Toutes les répétitions', eliminar:'Supprimer',
    queDeseasEliminar:'Que voulez-vous supprimer?',
    bienvenidoTitulo:'Bienvenue sur Syng!',
    bienvenidoMsg:'Vous explorez en tant qu invité. Connectez-vous gratuitement pour sauvegarder vos tâches.',
    iniciarSesion:'Se connecter', seguirExplorando:'Continuer à explorer',
    cargandoPizarron:'Chargement du tableau...',
    buscarGrupo:'Rechercher un groupe...', nuevoGrupoOpcion:'Nouveau groupe',
    moviendo:'déplacement...', reordenando:'réorganisation...',
    masDe:'plus',
    super:'Liste de Courses', superDesc:'Courses avec catalogue',
    listSuper:'Liste de Courses', productos:'produits',
    nuevoGrupoSuper:'+ Nouveau groupe', catalogo:'Catalogue', miLista:'Ma liste',
    buscarCatalogo:'Rechercher dans le catalogue...', buscarLista:'Rechercher dans ma liste...',
    sinResultados:'Aucun résultat pour', agregarProd:'+ ajouter',
    tocaCirculo:'Appuyez sur le cercle ou le texte pour marquer comme pris',
    seleccionar:'Sélectionner', seleccionados:'sélectionné(s)',
    borrarMarcados:'Supprimer marqués', borrarLista:'Vider la liste',
    misGrupos:'Mes groupes', integrantes:'membres', cerrar:'Fermer',
    nombreGrupoPlaceholder:'Nom du groupe (ex. Amis)',
    nombreProd:'Nom du produit', agregarA:'Ajouter à',
    editarProd:'Modifier le produit', nombre:'Nom', guardar:'Enregistrer',
    confirmarEliminarProd:'Ce produit sera supprimé de votre catalogue personnel.',
    confirmarEliminarLista:'Ils seront retirés de votre liste actuelle.',
    confirmarBorrarMarcados:'Supprimer les marqués?',
    confirmarBorrarLista:'Tous les produits seront supprimés de votre liste actuelle.',
    seleccionarProd:'Sélectionnez des produits du catalogue pour créer votre liste',
    apariencia:'Apparence', modoOscuro:'Mode sombre', modoClaro:'Mode clair',
    idioma:'Langue', privacidad:'Confidentialité', cerrarSesion:'Déconnexion',
    miPerfil:'Mon profil', configuracion:'Paramètres',
    instalarSyng:'Installer Syng', instalarDesc:"Ajouter l'app à votre écran d'accueil",
    instalarTitulo:'Installer Syng?',
    instalarIos:"Dans Safari: appuyez sur Partager et sélectionnez Ajouter à l'écran d'accueil",
    instalarAndroid:"Accédez plus rapidement depuis votre écran d'accueil",
    ahoraNO:'Pas maintenant', compartirSyng:'Partager Syng',
    version:'Syng v2.61 — Fait avec amour 🖤',
    vozVoz:'fr-FR',
    sinyiSaludo:'Comment puis-je vous aider?', sinyiDime:'Dites-moi, comment puis-je aider?',
    sinyiError:"Je n'ai pas entendu. Pouvez-vous répéter?",
    sinyiSistema:"Vous êtes Sinyi, assistante vocale de l'app Syng. Vous êtes une femme intelligente et chaleureuse. Répondez toujours en français, très brièvement, maximum 2 phrases.",
    agendaTitulo:'Mon Agenda', agendaSinPendientes:'Aucune tâche ce jour',
    agendaGuardarEn:'Enregistrer dans', agendaPizarron:'Quel tableau?',
    agendaNuevaTarea:'Quoi de prévu?', agendaAgregar:'+ ajouter',
    agendaGuardar:'Enregistrer', agendaCancelar:'Annuler', agendaEliminar:'Supprimer',
    agendaGuardarCambios:'Sauvegarder', agendaCambiarFecha:'Changer date',
    agendaRepetirFechas:'Répéter sur plus de dates',
    agendaConfirmarEliminar:'Supprimer cette tâche?', agendaSi:'Oui, supprimer',
    agendaMoverA:'Touchez le jour cible', agendaCopiarEn:'Touchez les jours à copier',
    agendaFechasSel:'date(s) sélectionnée(s)', agendaRepetir:'Répéter',
    meses:['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Décembre'],
    mesesCorto:['Jan','Fév','Mar','Avr','Mai','Jun','Jul','Aoû','Sep','Oct','Nov','Déc'],
    diasSemana:['Dim','Lun','Mar','Mer','Jeu','Ven','Sam'],
    diasSemanaCorto:['L','M','M','J','V','S','D'],
  },
  de: {
    iniciar:'Anmelden', registrar:'Registrieren', correo:'E-Mail-Adresse',
    contrasena:'Passwort', entrar:'Anmelden', crear:'Konto erstellen',
    oCon:'oder weiter mit', google:'Mit Google fortfahren', cargando:'Wird geladen...',
    errorCred:'Falsche E-Mail oder Passwort', errorCampos:'Bitte E-Mail und Passwort eingeben',
    errorGoogle:'Fehler bei Google-Anmeldung', eligeIdioma:'Wähle deine Sprache',
    slogan:'Synchronisiere deine Welt',
    inicio:'Start', perfil:'Profil', super2:'Einkauf', compartir:'Teilen',
    hola:'Hallo', queOrganizar:'Was möchtest du heute organisieren?',
    pendientesHoy:'ausstehend heute', pendientes:'Ausstehend', completadas:'Erledigt',
    misModulos:'MEINE MODULE',
    pendientesPizarron:'Heute ausstehend nach Board', completadasPizarron:'Heute erledigt nach Board',
    sinTareas:'Keine Aufgaben anzuzeigen',
    miAgenda:'Mein Kalender', miAgendaDesc:'Alle Aufgaben an einem Ort',
    pizarron:'Board', pizarronDesc:'Kollaborativer Kalender',
    misPizarrones:'Meine Boards', personal:'Persönlich', soloYo:'Nur ich',
    miembros:'Mitglieder', administrador:'Admin', miembro:'Mitglied',
    nuevoPizarron:'Neues gemeinsames Board', nuevoGrupo:'Neue Gruppe',
    nombreGrupo:'Gruppenname', crearGrupo:'Erstellen', cancelar:'Abbrechen',
    invitarGrupo:'In Gruppe einladen', invitandoGrupo:'Einladung wird gesendet...',
    linkUnico:'Jeder Link funktioniert einmal. Sie können so viele generieren wie nötig.',
    salirGrupo:'Gruppe verlassen', eliminarGrupo:'Gruppe löschen',
    confirmarSalir:'Gruppe verlassen?', confirmarSalirMsg:'Sie sehen das Board dieser Gruppe nicht mehr.',
    confirmarEliminarGrupo:'Gruppe löschen?', confirmarEliminarGrupoMsg:'Es wird für alle gelöscht und alle Notizen gehen verloren.',
    quitarMiembro:'Entfernen', confirmarQuitar:'Entfernen', confirmarQuitarMsg:'Sie werden aus der Gruppe entfernt.',
    pendientesLabel:'Ausstehend', atendidasLabel:'Erledigt',
    nuevaAnotacion:'Neue Notiz...', repetir:'Wiederholen',
    cambiarFecha:'Datum ändern', repetirFechas:'Auf mehr Daten wiederholen',
    moverA:'Tippe auf den Tag, zu dem du diese Notiz verschieben möchtest',
    copiarEn:'Tippe auf die Tage, an denen du diese Notiz kopieren möchtest',
    fechasSel:'Datum/Daten ausgewählt',
    sinAnotaciones:'Keine Notizen für diesen Tag',
    confirmarEliminar:'Aufgabe löschen?', soloEsta:'Nur dieses Datum',
    todasRepeticiones:'Alle Wiederholungen', eliminar:'Löschen',
    queDeseasEliminar:'Was möchtest du löschen?',
    bienvenidoTitulo:'Willkommen bei Syng!',
    bienvenidoMsg:'Sie erkunden als Gast. Melden Sie sich kostenlos an, um Ihre Aufgaben zu speichern.',
    iniciarSesion:'Anmelden', seguirExplorando:'Weiter erkunden',
    cargandoPizarron:'Board wird geladen...',
    buscarGrupo:'Gruppe suchen...', nuevoGrupoOpcion:'Neue Gruppe',
    moviendo:'verschieben...', reordenando:'neu anordnen...',
    masDe:'mehr',
    super:'Einkaufsliste', superDesc:'Einkaufen mit Katalog',
    listSuper:'Einkaufsliste', productos:'Produkte',
    nuevoGrupoSuper:'+ Neue Gruppe', catalogo:'Katalog', miLista:'Meine Liste',
    buscarCatalogo:'Im Katalog suchen...', buscarLista:'In meiner Liste suchen...',
    sinResultados:'Keine Ergebnisse für', agregarProd:'+ hinzufügen',
    tocaCirculo:'Kreis oder Text antippen um als abgeholt zu markieren',
    seleccionar:'Auswählen', seleccionados:'ausgewählt',
    borrarMarcados:'Markierte löschen', borrarLista:'Liste leeren',
    misGrupos:'Meine Gruppen', integrantes:'Mitglieder', cerrar:'Schließen',
    nombreGrupoPlaceholder:'Gruppenname (z.B. Freunde)',
    nombreProd:'Produktname', agregarA:'Hinzufügen zu',
    editarProd:'Produkt bearbeiten', nombre:'Name', guardar:'Speichern',
    confirmarEliminarProd:'Dieses Produkt wird aus Ihrem persönlichen Katalog entfernt.',
    confirmarEliminarLista:'Sie werden aus Ihrer aktuellen Liste entfernt.',
    confirmarBorrarMarcados:'Markierte löschen?',
    confirmarBorrarLista:'Alle Produkte werden aus Ihrer aktuellen Liste entfernt.',
    seleccionarProd:'Wählen Sie Produkte aus dem Katalog für Ihre Liste aus',
    apariencia:'Erscheinungsbild', modoOscuro:'Dunkelmodus', modoClaro:'Hellmodus',
    idioma:'Sprache', privacidad:'Datenschutz', cerrarSesion:'Abmelden',
    miPerfil:'Mein Profil', configuracion:'Einstellungen',
    instalarSyng:'Syng installieren', instalarDesc:'App zum Startbildschirm hinzufügen',
    instalarTitulo:'Syng installieren?',
    instalarIos:'In Safari: Teilen antippen und Zum Home-Bildschirm hinzufügen wählen',
    instalarAndroid:'Schneller vom Startbildschirm aus zugreifen',
    ahoraNO:'Nicht jetzt', compartirSyng:'Syng teilen',
    version:'Syng v2.61 — Mit Liebe gemacht 🖤',
    vozVoz:'de-DE',
    sinyiSaludo:'Wie kann ich dir helfen?', sinyiDime:'Sag mir, wie kann ich helfen?',
    sinyiError:'Ich habe dich nicht gehört. Kannst du wiederholen?',
    sinyiSistema:'Du bist Sinyi, Sprachassistentin der Syng App. Du bist eine intelligente und warmherzige Frau. Antworte immer auf Deutsch, sehr kurz, maximal 2 Sätze.',
    agendaTitulo:'Mein Kalender', agendaSinPendientes:'Keine Aufgaben an diesem Tag',
    agendaGuardarEn:'Speichern in', agendaPizarron:'Welches Board?',
    agendaNuevaTarea:'Was steht an?', agendaAgregar:'+ hinzufügen',
    agendaGuardar:'Speichern', agendaCancelar:'Abbrechen', agendaEliminar:'Löschen',
    agendaGuardarCambios:'Änderungen speichern', agendaCambiarFecha:'Datum ändern',
    agendaRepetirFechas:'Auf mehr Daten wiederholen',
    agendaConfirmarEliminar:'Aufgabe löschen?', agendaSi:'Ja, löschen',
    agendaMoverA:'Tag antippen zum Verschieben', agendaCopiarEn:'Tage antippen zum Kopieren',
    agendaFechasSel:'Datum/Daten ausgewählt', agendaRepetir:'Wiederholen',
    meses:['Januar','Februar','März','April','Mai','Juni','Juli','August','September','Oktober','November','Dezember'],
    mesesCorto:['Jan','Feb','Mär','Apr','Mai','Jun','Jul','Aug','Sep','Okt','Nov','Dez'],
    diasSemana:['So','Mo','Di','Mi','Do','Fr','Sa'],
    diasSemanaCorto:['M','D','M','D','F','S','S'],
  },
  it: {
    iniciar:'Accedi', registrar:'Registrati', correo:'Indirizzo email',
    contrasena:'Password', entrar:'Accedi', crear:'Crea account',
    oCon:'o continua con', google:'Continua con Google', cargando:'Caricamento...',
    errorCred:'Email o password errati', errorCampos:'Inserisci email e password',
    errorGoogle:'Errore accesso con Google', eligeIdioma:'Scegli la tua lingua',
    slogan:'Sincronizza il tuo mondo',
    inicio:'Home', perfil:'Profilo', super2:'Spesa', compartir:'Condividi',
    hola:'Ciao', queOrganizar:'Cosa vuoi organizzare oggi?',
    pendientesHoy:'in sospeso oggi', pendientes:'In sospeso', completadas:'Completate',
    misModulos:'I MIEI MODULI',
    pendientesPizarron:'In sospeso oggi per lavagna', completadasPizarron:'Completate oggi per lavagna',
    sinTareas:'Nessuna attività da mostrare',
    miAgenda:'La Mia Agenda', miAgendaDesc:'Tutte le tue attività in un unico posto',
    pizarron:'Lavagna', pizarronDesc:'Calendario collaborativo',
    misPizarrones:'Le Mie Lavagne', personal:'Personale', soloYo:'Solo io',
    miembros:'Membri', administrador:'Admin', miembro:'Membro',
    nuevoPizarron:'Nuova lavagna condivisa', nuevoGrupo:'Nuovo gruppo',
    nombreGrupo:'Nome del gruppo', crearGrupo:'Crea', cancelar:'Annulla',
    invitarGrupo:'Invita al gruppo', invitandoGrupo:"Invio dell'invito...",
    linkUnico:"Ogni link funziona una sola volta. Puoi generarne quanti ne hai bisogno.",
    salirGrupo:'Lascia il gruppo', eliminarGrupo:'Elimina gruppo',
    confirmarSalir:'Lasciare il gruppo?', confirmarSalirMsg:'Non vedrai più la lavagna di questo gruppo.',
    confirmarEliminarGrupo:'Eliminare il gruppo?', confirmarEliminarGrupoMsg:'Verrà eliminato per tutti e le note andranno perse.',
    quitarMiembro:'Rimuovi', confirmarQuitar:'Rimuovi', confirmarQuitarMsg:'Verrà rimosso dal gruppo.',
    pendientesLabel:'In sospeso', atendidasLabel:'Completate',
    nuevaAnotacion:'Nuova nota...', repetir:'Ripeti',
    cambiarFecha:'Cambia data', repetirFechas:'Ripeti su più date',
    moverA:'Tocca il giorno in cui vuoi spostare questa nota',
    copiarEn:'Tocca i giorni in cui vuoi copiare questa nota',
    fechasSel:'data/e selezionata/e',
    sinAnotaciones:'Nessuna nota per questo giorno',
    confirmarEliminar:'Eliminare questa attività?', soloEsta:'Solo questa data',
    todasRepeticiones:'Tutte le ripetizioni', eliminar:'Elimina',
    queDeseasEliminar:'Cosa vuoi eliminare?',
    bienvenidoTitulo:'Benvenuto su Syng!',
    bienvenidoMsg:'Stai esplorando come ospite. Accedi gratuitamente per salvare le tue attività.',
    iniciarSesion:'Accedi', seguirExplorando:'Continua ad esplorare',
    cargandoPizarron:'Caricamento lavagna...',
    buscarGrupo:'Cerca gruppo...', nuevoGrupoOpcion:'Nuovo gruppo',
    moviendo:'spostamento...', reordenando:'riorganizzazione...',
    masDe:'altro',
    super:'Lista della Spesa', superDesc:'Spesa con catalogo',
    listSuper:'Lista della Spesa', productos:'prodotti',
    nuevoGrupoSuper:'+ Nuovo gruppo', catalogo:'Catalogo', miLista:'La mia lista',
    buscarCatalogo:'Cerca nel catalogo...', buscarLista:'Cerca nella mia lista...',
    sinResultados:'Nessun risultato per', agregarProd:'+ aggiungi',
    tocaCirculo:'Tocca il cerchio o il testo per segnare come preso',
    seleccionar:'Seleziona', seleccionados:'selezionato/i',
    borrarMarcados:'Elimina segnati', borrarLista:'Svuota lista',
    misGrupos:'I miei gruppi', integrantes:'membri', cerrar:'Chiudi',
    nombreGrupoPlaceholder:'Nome del gruppo (es. Amici)',
    nombreProd:'Nome del prodotto', agregarA:'Aggiungi a',
    editarProd:'Modifica prodotto', nombre:'Nome', guardar:'Salva',
    confirmarEliminarProd:'Questo prodotto verrà rimosso dal tuo catalogo personale.',
    confirmarEliminarLista:'Verranno rimossi dalla tua lista attuale.',
    confirmarBorrarMarcados:'Eliminare i segnati?',
    confirmarBorrarLista:'Tutti i prodotti verranno rimossi dalla tua lista attuale.',
    seleccionarProd:'Seleziona prodotti dal catalogo per creare la tua lista',
    apariencia:'Aspetto', modoOscuro:'Modalità scura', modoClaro:'Modalità chiara',
    idioma:'Lingua', privacidad:'Privacy', cerrarSesion:'Esci',
    miPerfil:'Il mio profilo', configuracion:'Impostazioni',
    instalarSyng:'Installa Syng', instalarDesc:"Aggiungi l'app alla schermata iniziale",
    instalarTitulo:'Installare Syng?',
    instalarIos:"In Safari: tocca Condividi e seleziona Aggiungi alla schermata iniziale",
    instalarAndroid:'Accedi più velocemente dalla schermata iniziale',
    ahoraNO:'Non ora', compartirSyng:'Condividi Syng',
    version:'Syng v2.61 — Fatto con amore 🖤',
    vozVoz:'it-IT',
    sinyiSaludo:'Come posso aiutarti?', sinyiDime:'Dimmi, come posso aiutarti?',
    sinyiError:'Non ti ho sentito. Puoi ripetere?',
    sinyiSistema:"Sei Sinyi, assistente vocale dell'app Syng. Sei una donna intelligente e calorosa. Rispondi sempre in italiano, molto brevemente, massimo 2 frasi.",
    agendaTitulo:'La Mia Agenda', agendaSinPendientes:'Nessun compito questo giorno',
    agendaGuardarEn:'Salva in', agendaPizarron:'Quale lavagna?',
    agendaNuevaTarea:'Cosa hai in sospeso?', agendaAgregar:'+ aggiungi',
    agendaGuardar:'Salva', agendaCancelar:'Annulla', agendaEliminar:'Elimina',
    agendaGuardarCambios:'Salva modifiche', agendaCambiarFecha:'Cambia data',
    agendaRepetirFechas:'Ripeti in più date',
    agendaConfirmarEliminar:'Eliminare questa attività?', agendaSi:'Sì, elimina',
    agendaMoverA:'Tocca il giorno di destinazione', agendaCopiarEn:'Tocca i giorni dove copiare',
    agendaFechasSel:'data/e selezionata/e', agendaRepetir:'Ripeti',
    meses:['Gennaio','Febbraio','Marzo','Aprile','Maggio','Giugno','Luglio','Agosto','Settembre','Ottobre','Novembre','Dicembre'],
    mesesCorto:['Gen','Feb','Mar','Apr','Mag','Giu','Lug','Ago','Set','Ott','Nov','Dic'],
    diasSemana:['Dom','Lun','Mar','Mer','Gio','Ven','Sab'],
    diasSemanaCorto:['L','M','M','G','V','S','D'],
  },
  pt: {
    iniciar:'Entrar', registrar:'Cadastrar', correo:'Endereço de e-mail',
    contrasena:'Senha', entrar:'Entrar', crear:'Criar conta',
    oCon:'ou continue com', google:'Continuar com Google', cargando:'Carregando...',
    errorCred:'E-mail ou senha incorretos', errorCampos:'Digite seu e-mail e senha',
    errorGoogle:'Erro ao entrar com Google', eligeIdioma:'Escolha seu idioma',
    slogan:'Sincronize seu mundo',
    inicio:'Início', perfil:'Perfil', super2:'Compras', compartir:'Compartilhar',
    hola:'Olá', queOrganizar:'O que você quer organizar hoje?',
    pendientesHoy:'pendentes hoje', pendientes:'Pendentes', completadas:'Concluídas',
    misModulos:'MEUS MÓDULOS',
    pendientesPizarron:'Pendentes hoje por quadro', completadasPizarron:'Concluídas hoje por quadro',
    sinTareas:'Sem tarefas para mostrar',
    miAgenda:'Minha Agenda', miAgendaDesc:'Todas as suas tarefas em um só lugar',
    pizarron:'Quadro', pizarronDesc:'Calendário colaborativo',
    misPizarrones:'Meus Quadros', personal:'Pessoal', soloYo:'Só eu',
    miembros:'Membros', administrador:'Admin', miembro:'Membro',
    nuevoPizarron:'Novo quadro compartilhado', nuevoGrupo:'Novo grupo',
    nombreGrupo:'Nome do grupo', crearGrupo:'Criar', cancelar:'Cancelar',
    invitarGrupo:'Convidar para o grupo', invitandoGrupo:'Enviando convite...',
    linkUnico:'Cada link funciona uma vez. Você pode gerar quantos precisar.',
    salirGrupo:'Sair do grupo', eliminarGrupo:'Excluir grupo',
    confirmarSalir:'Sair do grupo?', confirmarSalirMsg:'Você não verá mais o quadro deste grupo.',
    confirmarEliminarGrupo:'Excluir grupo?', confirmarEliminarGrupoMsg:'Será excluído para todos e as notas serão perdidas.',
    quitarMiembro:'Remover', confirmarQuitar:'Remover', confirmarQuitarMsg:'Ele será removido do grupo.',
    pendientesLabel:'Pendentes', atendidasLabel:'Concluídas',
    nuevaAnotacion:'Nova nota...', repetir:'Repetir',
    cambiarFecha:'Alterar data', repetirFechas:'Repetir em mais datas',
    moverA:'Toque no dia para onde deseja mover esta nota',
    copiarEn:'Toque nos dias onde deseja copiar esta nota',
    fechasSel:'data(s) selecionada(s)',
    sinAnotaciones:'Sem notas para este dia',
    confirmarEliminar:'Excluir esta tarefa?', soloEsta:'Apenas esta data',
    todasRepeticiones:'Todas as repetições', eliminar:'Excluir',
    queDeseasEliminar:'O que você deseja excluir?',
    bienvenidoTitulo:'Bem-vindo ao Syng!',
    bienvenidoMsg:'Você está explorando como convidado. Entre gratuitamente para salvar suas tarefas.',
    iniciarSesion:'Entrar', seguirExplorando:'Continuar explorando',
    cargandoPizarron:'Carregando quadro...',
    buscarGrupo:'Buscar grupo...', nuevoGrupoOpcion:'Novo grupo',
    moviendo:'movendo...', reordenando:'reordenando...',
    masDe:'mais',
    super:'Lista de Compras', superDesc:'Compras com catálogo',
    listSuper:'Lista de Compras', productos:'produtos',
    nuevoGrupoSuper:'+ Novo grupo', catalogo:'Catálogo', miLista:'Minha lista',
    buscarCatalogo:'Pesquisar no catálogo...', buscarLista:'Pesquisar na minha lista...',
    sinResultados:'Sem resultados para', agregarProd:'+ adicionar',
    tocaCirculo:'Toque no círculo ou texto para marcar como pego',
    seleccionar:'Selecionar', seleccionados:'selecionado(s)',
    borrarMarcados:'Excluir marcados', borrarLista:'Limpar lista',
    misGrupos:'Meus grupos', integrantes:'membros', cerrar:'Fechar',
    nombreGrupoPlaceholder:'Nome do grupo (ex. Amigos)',
    nombreProd:'Nome do produto', agregarA:'Adicionar a',
    editarProd:'Editar produto', nombre:'Nome', guardar:'Salvar',
    confirmarEliminarProd:'Este produto será removido do seu catálogo pessoal.',
    confirmarEliminarLista:'Eles serão removidos da sua lista atual.',
    confirmarBorrarMarcados:'Excluir marcados?',
    confirmarBorrarLista:'Todos os produtos serão removidos da sua lista atual.',
    seleccionarProd:'Selecione produtos do catálogo para montar sua lista',
    apariencia:'Aparência', modoOscuro:'Modo escuro', modoClaro:'Modo claro',
    idioma:'Idioma', privacidad:'Privacidade', cerrarSesion:'Sair',
    miPerfil:'Meu perfil', configuracion:'Configurações',
    instalarSyng:'Instalar Syng', instalarDesc:'Adicionar o app à tela inicial',
    instalarTitulo:'Instalar Syng?',
    instalarIos:'No Safari: toque em Compartilhar e selecione Adicionar à tela inicial',
    instalarAndroid:'Acesse mais rápido pela tela inicial',
    ahoraNO:'Agora não', compartirSyng:'Compartilhar Syng',
    version:'Syng v2.61 — Feito com amor 🖤',
    vozVoz:'pt-BR',
    sinyiSaludo:'Como posso te ajudar?', sinyiDime:'Me diga, como posso ajudar?',
    sinyiError:'Não ouvi bem. Pode repetir?',
    sinyiSistema:'Você é Sinyi, assistente de voz do app Syng. Você é uma mulher inteligente e calorosa. Responda sempre em português, muito brevemente, máximo 2 frases.',
    agendaTitulo:'Minha Agenda', agendaSinPendientes:'Sem tarefas este dia',
    agendaGuardarEn:'Salvar em', agendaPizarron:'Qual quadro?',
    agendaNuevaTarea:'O que está pendente?', agendaAgregar:'+ adicionar',
    agendaGuardar:'Salvar', agendaCancelar:'Cancelar', agendaEliminar:'Excluir',
    agendaGuardarCambios:'Salvar alterações', agendaCambiarFecha:'Alterar data',
    agendaRepetirFechas:'Repetir em mais datas',
    agendaConfirmarEliminar:'Excluir esta tarefa?', agendaSi:'Sim, excluir',
    agendaMoverA:'Toque no dia de destino', agendaCopiarEn:'Toque nos dias para copiar',
    agendaFechasSel:'data(s) selecionada(s)', agendaRepetir:'Repetir',
    meses:['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
    mesesCorto:['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],
    diasSemana:['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'],
    diasSemanaCorto:['S','T','Q','Q','S','S','D'],
  },
  ja: {
    iniciar:'ログイン', registrar:'登録', correo:'メールアドレス',
    contrasena:'パスワード', entrar:'ログイン', crear:'アカウント作成',
    oCon:'または', google:'Googleで続ける', cargando:'読み込み中...',
    errorCred:'メールまたはパスワードが正しくありません', errorCampos:'メールとパスワードを入力してください',
    errorGoogle:'Googleログインエラー', eligeIdioma:'言語を選択',
    slogan:'世界を同期する',
    inicio:'ホーム', perfil:'プロフィール', super2:'買い物', compartir:'共有',
    hola:'こんにちは', queOrganizar:'今日は何を整理しますか？',
    pendientesHoy:'本日の保留中', pendientes:'保留中', completadas:'完了',
    misModulos:'マイモジュール',
    pendientesPizarron:'本日の保留中（ボード別）', completadasPizarron:'本日の完了（ボード別）',
    sinTareas:'表示するタスクなし',
    miAgenda:'マイアジェンダ', miAgendaDesc:'すべてのタスクを一か所で',
    pizarron:'ボード', pizarronDesc:'リアルタイム共同カレンダー',
    misPizarrones:'マイボード', personal:'個人', soloYo:'自分だけ',
    miembros:'メンバー', administrador:'管理者', miembro:'メンバー',
    nuevoPizarron:'新しい共有ボード', nuevoGrupo:'新しいグループ',
    nombreGrupo:'グループ名', crearGrupo:'作成', cancelar:'キャンセル',
    invitarGrupo:'グループに招待', invitandoGrupo:'招待を送信中...',
    linkUnico:'各リンクは一度だけ機能します。必要な数だけ生成できます。',
    salirGrupo:'グループを退出', eliminarGrupo:'グループを削除',
    confirmarSalir:'グループを退出しますか？', confirmarSalirMsg:'このグループのボードが見えなくなります。',
    confirmarEliminarGrupo:'グループを削除しますか？', confirmarEliminarGrupoMsg:'全員に対して削除され、すべてのメモが失われます。',
    quitarMiembro:'削除', confirmarQuitar:'削除', confirmarQuitarMsg:'グループから削除されます。',
    pendientesLabel:'保留中', atendidasLabel:'完了',
    nuevaAnotacion:'新しいメモ...', repetir:'繰り返す',
    cambiarFecha:'日付を変更', repetirFechas:'他の日に繰り返す',
    moverA:'このメモを移動したい日をタップ',
    copiarEn:'このメモをコピーしたい日をタップ',
    fechasSel:'日付選択済み',
    sinAnotaciones:'この日のメモなし',
    confirmarEliminar:'このタスクを削除しますか？', soloEsta:'この日付のみ',
    todasRepeticiones:'すべての繰り返し', eliminar:'削除',
    queDeseasEliminar:'何を削除しますか？',
    bienvenidoTitulo:'Syngへようこそ！',
    bienvenidoMsg:'ゲストとして探索中です。タスクを保存するために無料でサインインしてください。',
    iniciarSesion:'ログイン', seguirExplorando:'探索を続ける',
    cargandoPizarron:'ボードを読み込み中...',
    buscarGrupo:'グループを検索...', nuevoGrupoOpcion:'新しいグループ',
    moviendo:'移動中...', reordenando:'並び替え中...',
    masDe:'他',
    super:'買い物リスト', superDesc:'カタログ付き買い物',
    listSuper:'買い物リスト', productos:'商品',
    nuevoGrupoSuper:'+ 新しいグループ', catalogo:'カタログ', miLista:'マイリスト',
    buscarCatalogo:'カタログを検索...', buscarLista:'マイリストを検索...',
    sinResultados:'結果なし', agregarProd:'+ 追加',
    tocaCirculo:'円またはテキストをタップして取得済みとしてマーク',
    seleccionar:'選択', seleccionados:'選択済み',
    borrarMarcados:'マーク済みを削除', borrarLista:'リストをクリア',
    misGrupos:'マイグループ', integrantes:'メンバー', cerrar:'閉じる',
    nombreGrupoPlaceholder:'グループ名（例：友達）',
    nombreProd:'商品名', agregarA:'追加先',
    editarProd:'商品を編集', nombre:'名前', guardar:'保存',
    confirmarEliminarProd:'この商品は個人カタログから削除されます。',
    confirmarEliminarLista:'現在のリストから削除されます。',
    confirmarBorrarMarcados:'マーク済みを削除しますか？',
    confirmarBorrarLista:'現在のリストからすべての商品が削除されます。',
    seleccionarProd:'カタログから商品を選択してリストを作成してください',
    apariencia:'外観', modoOscuro:'ダークモード', modoClaro:'ライトモード',
    idioma:'言語', privacidad:'プライバシー', cerrarSesion:'ログアウト',
    miPerfil:'マイプロフィール', configuracion:'設定',
    instalarSyng:'Syngをインストール', instalarDesc:'アプリをホーム画面に追加',
    instalarTitulo:'Syngをインストールしますか？',
    instalarIos:'Safariで共有をタップしてホーム画面に追加を選択',
    instalarAndroid:'ホーム画面からすばやくアクセス',
    ahoraNO:'今はしない', compartirSyng:'Syngを共有',
    version:'Syng v2.61 — 愛を込めて作りました 🖤',
    vozVoz:'ja-JP',
    sinyiSaludo:'どのようにお手伝いできますか？', sinyiDime:'どうぞ、お手伝いします',
    sinyiError:'よく聞こえませんでした。もう一度言っていただけますか？',
    sinyiSistema:'あなたはSinyiです。Syngアプリの音声アシスタントです。インテリジェントで温かみのある女性として、常に日本語で簡潔に、最大2文で回答してください。',
    agendaTitulo:'マイアジェンダ', agendaSinPendientes:'この日のタスクなし',
    agendaGuardarEn:'保存先', agendaPizarron:'どのボード？',
    agendaNuevaTarea:'何が保留中ですか？', agendaAgregar:'+ 追加',
    agendaGuardar:'保存', agendaCancelar:'キャンセル', agendaEliminar:'削除',
    agendaGuardarCambios:'変更を保存', agendaCambiarFecha:'日付を変更',
    agendaRepetirFechas:'他の日に繰り返す',
    agendaConfirmarEliminar:'このタスクを削除しますか？', agendaSi:'はい、削除',
    agendaMoverA:'移動先の日をタップ', agendaCopiarEn:'コピーする日をタップ',
    agendaFechasSel:'日付選択済み', agendaRepetir:'繰り返す',
    meses:['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'],
    mesesCorto:['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'],
    diasSemana:['日','月','火','水','木','金','土'],
    diasSemanaCorto:['月','火','水','木','金','土','日'],
  },
  zh: {
    iniciar:'登录', registrar:'注册', correo:'电子邮件地址',
    contrasena:'密码', entrar:'登录', crear:'创建账户',
    oCon:'或继续使用', google:'使用Google继续', cargando:'加载中...',
    errorCred:'电子邮件或密码错误', errorCampos:'请输入您的电子邮件和密码',
    errorGoogle:'Google登录错误', eligeIdioma:'选择您的语言',
    slogan:'同步你的世界',
    inicio:'主页', perfil:'个人资料', super2:'购物', compartir:'分享',
    hola:'你好', queOrganizar:'今天想整理什么？',
    pendientesHoy:'今日待办', pendientes:'待办', completadas:'已完成',
    misModulos:'我的模块',
    pendientesPizarron:'今日待办（按白板）', completadasPizarron:'今日完成（按白板）',
    sinTareas:'没有任务可显示',
    miAgenda:'我的日程', miAgendaDesc:'所有待办事项集中在一处',
    pizarron:'白板', pizarronDesc:'实时协作日历',
    misPizarrones:'我的白板', personal:'个人', soloYo:'只有我',
    miembros:'成员', administrador:'管理员', miembro:'成员',
    nuevoPizarron:'新建共享白板', nuevoGrupo:'新建群组',
    nombreGrupo:'群组名称', crearGrupo:'创建', cancelar:'取消',
    invitarGrupo:'邀请加入群组', invitandoGrupo:'正在发送邀请...',
    linkUnico:'每个链接只能使用一次。您可以生成所需数量。',
    salirGrupo:'退出群组', eliminarGrupo:'删除群组',
    confirmarSalir:'退出群组？', confirmarSalirMsg:'您将不再看到此群组的白板。',
    confirmarEliminarGrupo:'删除群组？', confirmarEliminarGrupoMsg:'将为所有人删除，所有笔记将丢失。',
    quitarMiembro:'移除', confirmarQuitar:'移除', confirmarQuitarMsg:'他们将从群组中移除。',
    pendientesLabel:'待办', atendidasLabel:'已完成',
    nuevaAnotacion:'新建备注...', repetir:'重复',
    cambiarFecha:'更改日期', repetirFechas:'在更多日期重复',
    moverA:'点击您想将此备注移到的日期',
    copiarEn:'点击您想复制此备注的日期',
    fechasSel:'个日期已选择',
    sinAnotaciones:'这一天没有备注',
    confirmarEliminar:'删除此任务？', soloEsta:'仅此日期',
    todasRepeticiones:'所有重复', eliminar:'删除',
    queDeseasEliminar:'您想删除什么？',
    bienvenidoTitulo:'欢迎使用Syng！',
    bienvenidoMsg:'您正在以访客身份探索。免费登录以保存您的任务。',
    iniciarSesion:'登录', seguirExplorando:'继续探索',
    cargandoPizarron:'正在加载白板...',
    buscarGrupo:'搜索群组...', nuevoGrupoOpcion:'新建群组',
    moviendo:'移动中...', reordenando:'重新排序...',
    masDe:'更多',
    super:'购物清单', superDesc:'带目录的购物',
    listSuper:'购物清单', productos:'商品',
    nuevoGrupoSuper:'+ 新建群组', catalogo:'目录', miLista:'我的清单',
    buscarCatalogo:'搜索目录...', buscarLista:'搜索我的清单...',
    sinResultados:'没有结果', agregarProd:'+ 添加',
    tocaCirculo:'点击圆圈或文字标记为已取',
    seleccionar:'选择', seleccionados:'已选择',
    borrarMarcados:'删除已标记', borrarLista:'清空清单',
    misGrupos:'我的群组', integrantes:'成员', cerrar:'关闭',
    nombreGrupoPlaceholder:'群组名称（例：朋友）',
    nombreProd:'商品名称', agregarA:'添加到',
    editarProd:'编辑商品', nombre:'名称', guardar:'保存',
    confirmarEliminarProd:'此商品将从您的个人目录中删除。',
    confirmarEliminarLista:'它们将从您当前的清单中删除。',
    confirmarBorrarMarcados:'删除已标记的商品？',
    confirmarBorrarLista:'所有商品将从您当前的清单中删除。',
    seleccionarProd:'从目录中选择商品以创建您的清单',
    apariencia:'外观', modoOscuro:'深色模式', modoClaro:'浅色模式',
    idioma:'语言', privacidad:'隐私', cerrarSesion:'退出',
    miPerfil:'我的资料', configuracion:'设置',
    instalarSyng:'安装Syng', instalarDesc:'将应用添加到主屏幕',
    instalarTitulo:'安装Syng？',
    instalarIos:'在Safari中点击分享并选择添加到主屏幕',
    instalarAndroid:'从主屏幕更快地访问',
    ahoraNO:'暂不', compartirSyng:'分享Syng',
    version:'Syng v2.61 — 用爱制作 🖤',
    vozVoz:'zh-CN',
    sinyiSaludo:'我能帮您什么？', sinyiDime:'请说，我能帮您什么？',
    sinyiError:'我没有听清楚。您能重复一遍吗？',
    sinyiSistema:'你是Sinyi，Syng应用的语音助手。你是一位聪明热情的女性。始终用中文回答，非常简短，最多2句话。',
    agendaTitulo:'我的日程', agendaSinPendientes:'今天没有待办',
    agendaGuardarEn:'保存到', agendaPizarron:'哪个白板？',
    agendaNuevaTarea:'有什么待办？', agendaAgregar:'+ 添加',
    agendaGuardar:'保存', agendaCancelar:'取消', agendaEliminar:'删除',
    agendaGuardarCambios:'保存更改', agendaCambiarFecha:'更改日期',
    agendaRepetirFechas:'重复到更多日期',
    agendaConfirmarEliminar:'删除此任务？', agendaSi:'是的，删除',
    agendaMoverA:'点击目标日期', agendaCopiarEn:'点击要复制的日期',
    agendaFechasSel:'个日期已选择', agendaRepetir:'重复',
    meses:['一月','二月','三月','四月','五月','六月','七月','八月','九月','十月','十一月','十二月'],
    mesesCorto:['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'],
    diasSemana:['日','一','二','三','四','五','六'],
    diasSemanaCorto:['一','二','三','四','五','六','日'],
  },
}
